[phases.install]
cmds = ["npm --prefix kon-mee-barn ci"]

[phases.build]
cmds = ["npm --prefix kon-mee-barn run build"]

[start]
cmd = "cd kon-mee-barn && npx prisma db push && node_modules/.bin/next start -p ${PORT:-3000}"
