import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

const propertyImages = {
  house: [
    "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800",
    "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
    "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800",
  ],
  apartment: [
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
  ],
  condo: [
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
  ],
  commercial: [
    "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800",
    "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
  ],
};

const amenitiesList = ["Pool", "Gym", "Parking", "Security", "Garden", "Balcony", "Air Conditioning", "Elevator", "Pet Friendly", "Furnished"];

async function main() {
  console.log("Seeding database...");

  const password = await bcrypt.hash("password123", 12);

  // Create users
  const admin = await prisma.user.upsert({
    where: { email: "admin@konmeebarn.com" },
    update: {},
    create: { email: "admin@konmeebarn.com", password, name: "Admin User", role: "ADMIN" },
  });

  const seller1 = await prisma.user.upsert({
    where: { email: "seller1@example.com" },
    update: {},
    create: { email: "seller1@example.com", password, name: "Somchai Jaidee", role: "SELLER", phone: "081-234-5678" },
  });

  const seller2 = await prisma.user.upsert({
    where: { email: "seller2@example.com" },
    update: {},
    create: { email: "seller2@example.com", password, name: "Narin Srisuwan", role: "SELLER", phone: "082-345-6789" },
  });

  const landlord = await prisma.user.upsert({
    where: { email: "landlord@example.com" },
    update: {},
    create: { email: "landlord@example.com", password, name: "Praew Nakornthon", role: "LANDLORD", phone: "083-456-7890" },
  });

  const buyer1 = await prisma.user.upsert({
    where: { email: "buyer1@example.com" },
    update: {},
    create: { email: "buyer1@example.com", password, name: "Wanchai Phrommas", role: "BUYER", phone: "084-567-8901" },
  });

  const buyer2 = await prisma.user.upsert({
    where: { email: "buyer2@example.com" },
    update: {},
    create: { email: "buyer2@example.com", password, name: "Supaporn Kaewtong", role: "BUYER" },
  });

  console.log("Users created");

  // Delete existing properties
  await prisma.message.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.property.deleteMany();

  const properties = [
    // Bangkok - For Sale
    {
      title: "Modern 3BR House in Sukhumvit",
      description: "Stunning modern house in the heart of Sukhumvit. Features open-plan living, gourmet kitchen, and private garden. Walking distance to BTS stations and top international schools.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 8500000,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1800,
      address: "123 Sukhumvit Soi 49",
      city: "Bangkok",
      latitude: 13.7308,
      longitude: 100.5695,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[0], propertyImages.house[1]]),
      amenities: JSON.stringify(["Garden", "Air Conditioning", "Parking", "Security"]),
      ownerId: seller1.id,
    },
    {
      title: "Luxury Condo at Asoke - City View",
      description: "High-rise luxury condominium on the 28th floor with panoramic city views. Fully furnished with designer furniture. Access to rooftop pool and sky lounge.",
      propertyType: "CONDO",
      transactionType: "SALE",
      price: 12000000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1200,
      address: "88 Asoke Road",
      city: "Bangkok",
      latitude: 13.7381,
      longitude: 100.5603,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[0], propertyImages.condo[1]]),
      amenities: JSON.stringify(["Pool", "Gym", "Elevator", "Security", "Furnished"]),
      ownerId: seller1.id,
    },
    {
      title: "Charming Townhouse in Thonglor",
      description: "3-storey townhouse in trendy Thonglor neighborhood. Renovated kitchen and bathrooms. Small private garden. Easy access to nightlife, cafes, and restaurants.",
      propertyType: "TOWNHOUSE",
      transactionType: "SALE",
      price: 6800000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 2200,
      address: "45/3 Thonglor Soi 10",
      city: "Bangkok",
      latitude: 13.7253,
      longitude: 100.5784,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[2], propertyImages.house[0]]),
      amenities: JSON.stringify(["Garden", "Parking", "Air Conditioning"]),
      ownerId: seller2.id,
    },
    {
      title: "Investment Apartment Building - Ladprao",
      description: "Commercial apartment building with 8 rental units fully occupied. Prime location near Central Ladprao. Excellent rental yield. Ideal for investors.",
      propertyType: "COMMERCIAL",
      transactionType: "SALE",
      price: 35000000,
      bedrooms: 0,
      bathrooms: 0,
      squareFeet: 5600,
      address: "222 Ladprao Road",
      city: "Bangkok",
      latitude: 13.8010,
      longitude: 100.5681,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.commercial[0], propertyImages.commercial[1]]),
      amenities: JSON.stringify(["Parking", "Security"]),
      ownerId: seller2.id,
    },
    {
      title: "Studio Apartment near Silom BTS",
      description: "Cozy studio apartment just 5 minutes walk from Chong Nonsi BTS. Fully furnished, perfect for young professionals. Building amenities include rooftop garden.",
      propertyType: "APARTMENT",
      transactionType: "SALE",
      price: 2200000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 380,
      address: "567 Silom Road",
      city: "Bangkok",
      latitude: 13.7290,
      longitude: 100.5290,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[0], propertyImages.apartment[1]]),
      amenities: JSON.stringify(["Furnished", "Air Conditioning", "Elevator"]),
      ownerId: seller1.id,
    },
    // Bangkok - For Rent
    {
      title: "Spacious 2BR Condo - Phrom Phong",
      description: "Bright and airy 2-bedroom condo in upscale Phrom Phong. 5 min walk to Emquartier and BTS. Fully equipped kitchen, large balcony with park view.",
      propertyType: "CONDO",
      transactionType: "RENT",
      price: 35000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 900,
      address: "30 Sukhumvit Soi 39",
      city: "Bangkok",
      latitude: 13.7272,
      longitude: 100.5681,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[2], propertyImages.condo[0]]),
      amenities: JSON.stringify(["Pool", "Gym", "Balcony", "Furnished", "Air Conditioning"]),
      ownerId: landlord.id,
    },
    {
      title: "Pet-Friendly Apartment - On Nut",
      description: "Comfortable pet-friendly apartment near On Nut BTS. Semi-furnished with air conditioning in all rooms. Large park nearby for dog walks.",
      propertyType: "APARTMENT",
      transactionType: "RENT",
      price: 18000,
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 700,
      address: "444 On Nut Road",
      city: "Bangkok",
      latitude: 13.7034,
      longitude: 100.5990,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[2], propertyImages.apartment[0]]),
      amenities: JSON.stringify(["Pet Friendly", "Air Conditioning", "Parking"]),
      ownerId: landlord.id,
    },
    {
      title: "Modern House for Rent - Bangna",
      description: "Newly built 4-bedroom house in quiet Bangna residential estate. Private pool, double garage, large garden. 10 minutes to Suvarnabhumi Airport.",
      propertyType: "HOUSE",
      transactionType: "RENT",
      price: 55000,
      bedrooms: 4,
      bathrooms: 3,
      squareFeet: 2800,
      address: "789 Bangna Trad Road",
      city: "Bangkok",
      latitude: 13.6728,
      longitude: 100.6711,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[1], propertyImages.house[2]]),
      amenities: JSON.stringify(["Pool", "Garden", "Parking", "Security", "Air Conditioning"]),
      ownerId: landlord.id,
    },
    {
      title: "Compact Studio - Victory Monument",
      description: "Affordable studio near Victory Monument BTS. Great for students and solo workers. 24-hour security, convenient store on ground floor.",
      propertyType: "APARTMENT",
      transactionType: "RENT",
      price: 8500,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 280,
      address: "12 Phaya Thai Road",
      city: "Bangkok",
      latitude: 13.7661,
      longitude: 100.5378,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[1], propertyImages.apartment[0]]),
      amenities: JSON.stringify(["Air Conditioning", "Elevator", "Security"]),
      ownerId: landlord.id,
    },
    {
      title: "Penthouse Condo - Sathorn",
      description: "Breathtaking penthouse with 360-degree city views. Private rooftop terrace, jacuzzi, and dedicated parking. Building has concierge and valet service.",
      propertyType: "CONDO",
      transactionType: "RENT",
      price: 120000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 2100,
      address: "1 Sathorn Road",
      city: "Bangkok",
      latitude: 13.7205,
      longitude: 100.5240,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[0], propertyImages.condo[2]]),
      amenities: JSON.stringify(["Pool", "Gym", "Security", "Parking", "Furnished", "Balcony", "Elevator"]),
      ownerId: landlord.id,
    },
    // Chiang Mai - For Sale
    {
      title: "Traditional Thai House with Garden - Nimmanhaemin",
      description: "Beautiful traditional Thai-style house with modern interiors. Large tropical garden, outdoor sala, fish pond. Walking distance to Nimman cafes and galleries.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 5200000,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 2000,
      address: "10 Nimmanhaemin Soi 7",
      city: "Chiang Mai",
      latitude: 18.8007,
      longitude: 98.9672,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[0], propertyImages.house[1]]),
      amenities: JSON.stringify(["Garden", "Parking", "Air Conditioning", "Security"]),
      ownerId: seller1.id,
    },
    {
      title: "Modern Pool Villa - Mae Rim",
      description: "Stunning contemporary pool villa in Mae Rim valley with mountain views. 4 bedrooms, infinity pool, outdoor kitchen. 20 minutes from Chiang Mai city center.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 14500000,
      bedrooms: 4,
      bathrooms: 4,
      squareFeet: 4200,
      address: "222 Mae Rim Road",
      city: "Chiang Mai",
      latitude: 18.9024,
      longitude: 98.9383,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[2], propertyImages.house[0]]),
      amenities: JSON.stringify(["Pool", "Garden", "Parking", "Security", "Air Conditioning"]),
      ownerId: seller2.id,
    },
    {
      title: "Cozy Condo near Chiang Mai University",
      description: "Well-maintained condo near CMU campus. Great investment for student rental income. Communal pool, gym, and shuttle to city center.",
      propertyType: "CONDO",
      transactionType: "SALE",
      price: 1800000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 450,
      address: "88 Suthep Road",
      city: "Chiang Mai",
      latitude: 18.7963,
      longitude: 98.9520,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[1], propertyImages.condo[2]]),
      amenities: JSON.stringify(["Pool", "Gym", "Elevator", "Air Conditioning"]),
      ownerId: seller1.id,
    },
    {
      title: "Land Plot - Doi Saket",
      description: "Prime land plot with mountain views in scenic Doi Saket area. Electricity and water available. Suitable for villa or resort development.",
      propertyType: "LAND",
      transactionType: "SALE",
      price: 3600000,
      bedrooms: 0,
      bathrooms: 0,
      squareFeet: 6400,
      address: "Doi Saket Sub-district",
      city: "Chiang Mai",
      latitude: 18.8745,
      longitude: 99.1356,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[1]]),
      amenities: JSON.stringify([]),
      ownerId: seller2.id,
    },
    // Chiang Mai - For Rent
    {
      title: "Stylish 1BR Apartment - Nimman Area",
      description: "Trendy apartment in the heart of Nimman. Steps from hip cafes, co-working spaces, and galleries. Fully furnished with contemporary design.",
      propertyType: "APARTMENT",
      transactionType: "RENT",
      price: 15000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 520,
      address: "55 Nimmanhaemin Road",
      city: "Chiang Mai",
      latitude: 18.7993,
      longitude: 98.9681,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[0], propertyImages.apartment[2]]),
      amenities: JSON.stringify(["Furnished", "Air Conditioning", "Pool", "Gym"]),
      ownerId: landlord.id,
    },
    {
      title: "Thai-Style Wooden House - Hang Dong",
      description: "Authentic teak wooden house in peaceful Hang Dong. Large shaded garden, outdoor kitchen, hammock area. 20 min from city, ideal for nature lovers.",
      propertyType: "HOUSE",
      transactionType: "RENT",
      price: 22000,
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 1100,
      address: "45 Hang Dong Road",
      city: "Chiang Mai",
      latitude: 18.6929,
      longitude: 98.9293,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[2], propertyImages.house[1]]),
      amenities: JSON.stringify(["Garden", "Parking", "Pet Friendly", "Air Conditioning"]),
      ownerId: landlord.id,
    },
    {
      title: "Budget Studio near Night Bazaar",
      description: "Affordable studio in central Chiang Mai. Close to Night Bazaar, Ping River, and Warorot Market. Shared rooftop with mountain views.",
      propertyType: "APARTMENT",
      transactionType: "RENT",
      price: 7000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 240,
      address: "12 Chang Klan Road",
      city: "Chiang Mai",
      latitude: 18.7866,
      longitude: 98.9985,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[1]]),
      amenities: JSON.stringify(["Air Conditioning", "Security"]),
      ownerId: landlord.id,
    },
    // Phuket - For Sale
    {
      title: "Beachfront Villa - Rawai",
      description: "Spectacular beachfront villa with direct sea access. 5 bedrooms, infinity pool, tropical garden. The ultimate luxury retreat on Thailand's most famous island.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 65000000,
      bedrooms: 5,
      bathrooms: 5,
      squareFeet: 6500,
      address: "1 Rawai Beach Road",
      city: "Phuket",
      latitude: 7.7834,
      longitude: 98.3290,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[0], propertyImages.house[1], propertyImages.house[2]]),
      amenities: JSON.stringify(["Pool", "Garden", "Parking", "Security", "Air Conditioning", "Balcony"]),
      ownerId: seller2.id,
    },
    {
      title: "Sea View Condo - Patong",
      description: "Modern condo with stunning Andaman Sea views from Patong. 2 bedrooms, fully furnished to hotel standard. Walking distance to Patong Beach.",
      propertyType: "CONDO",
      transactionType: "SALE",
      price: 7800000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 980,
      address: "88 Patong Hill Road",
      city: "Phuket",
      latitude: 7.8908,
      longitude: 98.3017,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[0], propertyImages.condo[2]]),
      amenities: JSON.stringify(["Pool", "Gym", "Elevator", "Security", "Furnished", "Balcony"]),
      ownerId: seller1.id,
    },
    {
      title: "Pool Villa - Chalong",
      description: "Gorgeous 3-bedroom pool villa in quiet Chalong area. Private garden, outdoor dining sala, BBQ area. Near Chalong Bay and Wat Chalong.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 18500000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 3200,
      address: "15 Chalong Road",
      city: "Phuket",
      latitude: 7.8163,
      longitude: 98.3554,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[2], propertyImages.house[0]]),
      amenities: JSON.stringify(["Pool", "Garden", "Parking", "Air Conditioning", "Security"]),
      ownerId: seller2.id,
    },
    {
      title: "Commercial Space - Phuket Town",
      description: "Prime commercial space in Phuket Town's Old Town district. Ground floor with high foot traffic. Ideal for restaurant, cafe, or retail. 3-year lease option available.",
      propertyType: "COMMERCIAL",
      transactionType: "LEASE",
      price: 85000,
      bedrooms: 0,
      bathrooms: 1,
      squareFeet: 1200,
      address: "30 Thalang Road",
      city: "Phuket",
      latitude: 7.8889,
      longitude: 98.3948,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.commercial[0], propertyImages.commercial[1]]),
      amenities: JSON.stringify(["Parking", "Air Conditioning"]),
      ownerId: seller1.id,
    },
    // Phuket - For Rent
    {
      title: "Tropical Villa with Pool - Nai Harn",
      description: "Beautiful tropical villa near Nai Harn beach. Private pool, open-plan living, tropical garden. 3 bedrooms, each with en-suite. Housekeeper available.",
      propertyType: "HOUSE",
      transactionType: "RENT",
      price: 85000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 3500,
      address: "22 Nai Harn Road",
      city: "Phuket",
      latitude: 7.7716,
      longitude: 98.3043,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[1], propertyImages.house[0]]),
      amenities: JSON.stringify(["Pool", "Garden", "Parking", "Security", "Air Conditioning", "Furnished"]),
      ownerId: landlord.id,
    },
    {
      title: "Budget Condo near Kata Beach",
      description: "Comfortable condo just 500m from Kata Beach. Shared pool and gym. Fully furnished with all appliances. Perfect for expats and long-stay guests.",
      propertyType: "CONDO",
      transactionType: "RENT",
      price: 18000,
      bedrooms: 1,
      bathrooms: 1,
      squareFeet: 550,
      address: "55 Kata Road",
      city: "Phuket",
      latitude: 7.8212,
      longitude: 98.2980,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[1], propertyImages.condo[0]]),
      amenities: JSON.stringify(["Pool", "Gym", "Furnished", "Air Conditioning", "Balcony"]),
      ownerId: landlord.id,
    },
    {
      title: "Apartment near Central Phuket",
      description: "Convenient apartment near Central Festival Phuket. 2 bedrooms, modern design, city view. Easy access to shops, restaurants, and public transport.",
      propertyType: "APARTMENT",
      transactionType: "RENT",
      price: 25000,
      bedrooms: 2,
      bathrooms: 1,
      squareFeet: 780,
      address: "10 Wichit Song Khram Road",
      city: "Phuket",
      latitude: 7.9046,
      longitude: 98.3929,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.apartment[2], propertyImages.apartment[1]]),
      amenities: JSON.stringify(["Air Conditioning", "Parking", "Elevator", "Security"]),
      ownerId: landlord.id,
    },
    // More Bangkok
    {
      title: "New Townhouse - Rama 9",
      description: "Brand new 3-storey townhouse in emerging Rama 9 district. Smart home features, solar panels, EV charging. Near MRT Rama 9 and Central Rama 9.",
      propertyType: "TOWNHOUSE",
      transactionType: "SALE",
      price: 4900000,
      bedrooms: 3,
      bathrooms: 3,
      squareFeet: 1900,
      address: "15 Rama 9 Soi 20",
      city: "Bangkok",
      latitude: 13.7556,
      longitude: 100.5678,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.house[0], propertyImages.house[2]]),
      amenities: JSON.stringify(["Parking", "Air Conditioning", "Security", "Garden"]),
      ownerId: seller2.id,
    },
    {
      title: "Office Space - Asok BTS",
      description: "Premium office space in Grade-A building at Asok BTS. 500 sqm open plan with meeting rooms. Fully fitted, ready to move in. Building gym and cafe.",
      propertyType: "COMMERCIAL",
      transactionType: "LEASE",
      price: 150000,
      bedrooms: 0,
      bathrooms: 2,
      squareFeet: 5000,
      address: "55 Sukhumvit 21",
      city: "Bangkok",
      latitude: 13.7370,
      longitude: 100.5597,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.commercial[1], propertyImages.commercial[0]]),
      amenities: JSON.stringify(["Air Conditioning", "Parking", "Security", "Elevator"]),
      ownerId: seller1.id,
    },
    {
      title: "Riverside Condo - Charoennakorn",
      description: "Stunning Chao Phraya river view condo in Iconsiam project area. 2 bedrooms, high floor, river and city views. Direct access to IconSiam mall.",
      propertyType: "CONDO",
      transactionType: "SALE",
      price: 9800000,
      bedrooms: 2,
      bathrooms: 2,
      squareFeet: 1050,
      address: "299 Charoennakorn Road",
      city: "Bangkok",
      latitude: 13.7207,
      longitude: 100.5094,
      status: "ACTIVE",
      images: JSON.stringify([propertyImages.condo[2], propertyImages.condo[0]]),
      amenities: JSON.stringify(["Pool", "Gym", "Elevator", "Security", "Balcony"]),
      ownerId: seller2.id,
    },
    // Pending listing
    {
      title: "Classic House - Wang Thonglang",
      description: "Classic 3-bedroom house in quiet Wang Thonglang neighborhood. Renovated bathrooms. Large yard with mature trees. Great for families.",
      propertyType: "HOUSE",
      transactionType: "SALE",
      price: 4200000,
      bedrooms: 3,
      bathrooms: 2,
      squareFeet: 1600,
      address: "78 Wang Thonglang Road",
      city: "Bangkok",
      latitude: 13.7648,
      longitude: 100.5982,
      status: "PENDING",
      images: JSON.stringify([propertyImages.house[1]]),
      amenities: JSON.stringify(["Garden", "Parking", "Air Conditioning"]),
      ownerId: seller1.id,
    },
  ];

  const created: any[] = [];
  for (const p of properties) {
    const prop = await prisma.property.create({ data: p });
    created.push(prop);
  }

  console.log(`Created ${created.length} properties`);

  // Create favorites
  const favData = [
    { userId: buyer1.id, propertyId: created[0].id },
    { userId: buyer1.id, propertyId: created[5].id },
    { userId: buyer1.id, propertyId: created[12].id },
    { userId: buyer2.id, propertyId: created[1].id },
    { userId: buyer2.id, propertyId: created[17].id },
  ];
  for (const fav of favData) {
    await prisma.favorite.create({ data: fav }).catch(() => {});
  }

  // Create messages
  const msgData = [
    {
      propertyId: created[0].id,
      senderId: buyer1.id,
      receiverId: seller1.id,
      content: "Hello, I'm interested in this property. Is the price negotiable?",
    },
    {
      propertyId: created[0].id,
      senderId: seller1.id,
      receiverId: buyer1.id,
      content: "Hi! Yes, there is some room for negotiation. When would you like to schedule a viewing?",
      read: true,
    },
    {
      propertyId: created[5].id,
      senderId: buyer2.id,
      receiverId: landlord.id,
      content: "Is this property still available? Can I view it this weekend?",
    },
  ];
  for (const msg of msgData) {
    await prisma.message.create({ data: msg }).catch(() => {});
  }

  console.log("Seed completed successfully!");
  console.log("\nTest accounts:");
  console.log("  Admin:    admin@konmeebarn.com / password123");
  console.log("  Seller:   seller1@example.com / password123");
  console.log("  Landlord: landlord@example.com / password123");
  console.log("  Buyer:    buyer1@example.com / password123");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
